export * from './ICliente'
export * from './IEndereco'
export * from './IDocumento'
export * from './ITelefone'
export * from './IDependente'
export * from './IAcomodacao'
export * from './IHospedagem'