export * from './dashboard/Dashboard'
export * from './cadastro-cliente/CadastroCliente'
export * from './editar-cliente/EditarCliente'
export * from './ver-cliente/VerCliente'
export * from './excluir-cliente/ExcluirCliente'
export * from './listagem-cliente/ListagemCliente'
export * from './cadastro-hospedagem/CadastroHospedagem'